---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: docs/index.md
  label: introduction
- type: directory
  path: docs/getting-started
  label: guides
  create: all
  match: "**/*"
- type: directory
  path: docs/common-terms
  label: dictionary
  create: all
  match: "**/*"  
- type: directory
  path: docs/ic-provider-api
  label: ic
  create: all
  match: "**/*"    
  - type: directory
  path: docs/resources
  label: resources
  create: all
  match: "**/*"    
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
